M48
; DRILL file {KiCad 9.0.3+dfsg-1} date 2026-02-22T16:32:25-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-22T16:32:25-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.000
%
G90
G05
T1
X143.0Y-51.0
X143.0Y-121.0
X176.0Y-51.0
X176.0Y-121.0
M30
